### ISSUE TITLE
Add support for smbus2 drivers

### ISSUE THREAD

**Issue by AndrewD** [zapta/greenpak#2]
There is a simple GreenPAK tool here: [okada-tetsuya/gpakutil](https://github.com/okada-tetsuya/gpakutil) that uses smbus to read/write GreenPAKs. It is documented to work on Raspberry Pi and I have used it successfully to read from a SLG46826 connected to a Beaglebone.

It would be interesting to add support for [smbus](https://pypi.org/project/smbus2/) so this tool can be used with a broader range of hardware. Is this something you are considering, or if not would you consider a PR to add this capability?

**Comment by zapta** [comment]
Hi Andrew,

That's an interesting idea

1. Do you think you can abstract it as new i2c driver class here
https://github.com/zapta/greenpak/blob/main/src/greenpak/i2c.py ?

2. I presume it will work only on Raspberry Pi and will require RPI only
packages. Is it so?  Will it be an issue for non RPI,  Mac/Windows/Linux
users?

Z/

**Comment by AndrewD** [comment]
> Hi Andrew, That's an interesting idea 1. Do you think you can abstract it as new i2c driver class here https://github.com/zapta/greenpak/blob/main/src/greenpak/i2c.py ?

This seemed feasible when I had a quick skim of the code, but I didn't look at the details.

>  2. I presume it will work only on Raspberry Pi and will require RPI only packages. Is it so? Will it be an issue for non RPI, Mac/Windows/Linux users?

This should work on any Linux platform that exposes a smbus driver. As mentioned I tried it on a Beaglebone - actually a [beaglebone green](https://www.beagleboard.org/boards/seeedstudio-beaglebone-green) but it should work on many other embedded Linux boards such as [A20-OLinuXino-MICRO](https://www.olimex.com/Products/OLinuXino/A20/A20-OLinuXino-MICRO/open-source-hardware).

The high level interface of your custom i2c layer seemed very similar to the python smbus2 wrapper but probably not identical. Maybe they could converge?

**Comment by zapta** [comment]
Yes, I think it should be ok. It doesn't need to work on all platforms as
long as the dependency on smbus2 doesn't break Windows/Mac, etc, so I think
it's OK.

The current i2c abstraction the greenpak package uses is very simple with
only a read() and a write() methods and I prefer to keep it this way. You
can see here a sample straight forward implementation using the I2C Driver
package https://github.com/zapta/greenpak/blob/main/src/greenpak/i2c.py#L67

I also found here an implementation of another I2C abstraction using smbus
which may help to develope the wrapper for the greenpak
https://github.com/rm-hull/luma.core/blob/master/luma/core/interface/serial.py#L25

Is it something that you would like to contribute? Do you have the
facilities to test it (e.g. a compatible host and a greenpak device)?

**Comment by AndrewD** [comment]
We have everything required - I have a colleague @dry-75 that will look at the options for implementation shortly.
