### ISSUE TITLE
GreenPakSMBusAdapter : bug : only reads from offset/register 0

### ISSUE THREAD

**Issue by dry-75** [zapta/greenpak#4]
Just saw that unless driver reads from register/offset 0  - in any block - it won't  return correct read unless full memory block was requested.

The greenpak' driver.py does write, read , where write puts out the target register of the next read call which does not get passed the register in question.  I don't see that we can split this write/read as required per SLG protocol - as e.g., required for reading a block of data in with no stop between write-read.

SMBus library it can do register(s) read in one call  -doing needed write, read underneath.

I'm wondering if better way if we could extend the GreenPakI2cInterface with _optional_ overridable read_registers(...) (or whatever name), taking register address and performing the entire op (write, read) behind the scenes? Supporting adapters would be free to implement it. But the GreenpakDriver would need to use that call , if interface provides it .. So I'm unsure.

Essentially, so this usual/current 2-steps of __read_bytes() in driver.py could be replaced with one call like  self.__i2c.read_registers(..... ) IFF the method was implemented.
`      ok = self.__i2c.write(device_i2c_addr, bytearray([start_address]))
        ....
        resp_bytes = self.__i2c.read(device_i2c_addr, n)
`
@zapta thoughts?

Otherwise at this moment I only see something ugly like saving register address on write request, then using it for the subsequent immediate read.  (And also, then the first write is of no use really if it' used for reading SLG).

**Comment by zapta** [comment]
Let me look at it and understand. If it requires write/read operation then it makes sense to implement it. The reason I went with this approach is that the I2C Adapter I am using currently supports only independent read and writes but this can be changed if needed.

As a short term workaround, can you read the entire page in your application and extract the bytes you need?  I presume that the extra read will not have any side effect on the GreenPAK.

**Comment by zapta** [comment]
Thinking about the driver abstractions, we could have a single transaction call to the driver that does both an optional write and an optional read together but then we need to specify the exceptions, e.g. when having to perform chunking which breaks the simple model.

Another option is to use the existing driver model and change the greenpak package itself to read from the start of the page and drop the unnecessary bytes before returning to the user. Do you see any problem with this approach? I presume that there are no side effect on the greenpak from reading arbitrary bytes.

**Comment by dry-75** [comment]
I would think that reading from desired address and only the desired amout of bytes certainly has value, rather than always reading entire memory block (i.e., 256 bytes of reg/nvm/eep).  E.g.:  say I have N of them on the same bus, and I would like to monitor only few pins (few bits in some registers) on each, by polling every M ms.  Something in fact I'm testing.

With GreenPak (slg) protocol, whether doing a single read from random register or a chunk of bytes starting at some register, a write first would always be needed, to set the destination register / start register. So I don't think the current greenpak's driver.py or I2C Adapter doing anything sub-optimal, they use I2C layer direct (as far as I remember looking at those..). SMBus2 library effectively builds on top of native I2C layer, and provides those read remote device adddress (or execute remote command) transactions without us writing it more elaborately.   So it was a quick/short way to plug onto Linux I2C layer.

May be I don't see something, but it's just one method in driver.py that ether a derived class can override, or when original driver initializes perhaps it can set the alternative __read_bytes() based on what interface adapter is passed.

I could try something out and show what I mean, in case this sounds unclear. I'm not Python pro however, more lower langauges and C++, so I don't guarantee it would be in best Python practices style.

**Comment by zapta** [comment]
Let's say that we will change the driver interface to allow write/read
operation. Something along these lines (pseudo code):

i2c_transaction (
    device_address,  // int
    write_data           // bytearray | null
    read_count          // int | null
)

Such that if write_data is not null then the transaction includes write
operation and if read_count is not null the transaction includes read
operation. At least one of write_data and read_count must be non null.

What are the restrictions of the i2C driver you are using? Is it
len(write_data) <= 32 and read_count <= 32 or (len(write_data) + read_count
)<= 32 ?

I am trying to figure out how to abstract it with the common driver
interface. For example, assuming these restrictions for all drivers, as the
lowest common requirement.

**Comment by dry-75** [comment]
> ..What are the restrictions of the i2C driver you are using? 
I prefer to think if it as, within context of  SMBus adapter, we know less of exact I2C layer used and more of direct interface we using, the library on top. So that layer works in transactions, seems mostly, and hides or impelments the steps behind.
It has that constant internally, which the adapter for greenpak driver has referred to, I think its set to 32, but it could be set to something else, say if the layer changes - so we just refer to their contant defined.

I mean we could skip SMBus2 library entirely and jump down to I2C layer below it and do this all SLG transactions 'manually' as the greenpak's own i2c driver does, but idea was for us to make this short & sweet, with less extra code writing and using more.  We would be replicating some efforts already done by the library for us.

**Comment by zapta** [comment]
That's also my goal, but to define a new abstract interface to the i2c
driver I need to understand the limitations of the i2c driver you use to
make sure it can fit.

What are the limitations of your driver, IIRC you mention 32 byte
limitation. For example, can it do a single write/read transaction with 32
byte write and then 32 bytes read?  Please specify that limitations so we
can design for it.

**Comment by dry-75** [comment]
The referred to constant would be the only limitation I have encountered as far as the smbus library adapter we have created. That adapter as merged, doesn't use I2C driver directly.

**Comment by dry-75** [comment]
I'm also thinking that, as an incremental or smalltest change/addition , you could do following. Consider class GreenPakI2cInterface spec as is now:
def write(self, addr: int, data: bytearray, silent: bool = False) -> bool
def read(   self, addr: int, byte_count: int, silent: bool = False ) -> bytearray | None

Add new method to be overridable (not catching on exact naming..):

    def read_request(self, addr: int, data: bytearray, silent: bool = False ):
        # By default of not overriden, implement exact steps as current driver.py does
        # in __read_bytes, that is ..
        self.write(...) 
        self.read(...) 
        # return  new data or nothing , similarly.
        # Thats default just to have something : it won't work mostly for Gp,
        # because for e.g.GreenPakI2cDriver() does __i2c.stop(), which would
        # violate SLG proto to read a chunk of data.
        # But this is that driver problem: any driver could override read_request
        # to make this work. 
        # For GreenPakSMBusAdapter, for .e.g. that would be an almost direct
        # mapping to its underl layer to single call as read_i2c_block_data(...)

Then, the minor update that driver.py would need is , within method:
def __read_bytes(....)
#  Replace that two stop __i2c.write(...) ,   __i2c.read(..) with the new invocation, :
__i2c.read_request(....)   , passing the i2c address, and similarly that bytearray with register/destination.

I could test this fairly quick on my platform.

( Side note:  as per my comment above, that the current GreenPakI2cDriver(...) has the issue of terminating transaction in both write() and read(), so I don't quite see this could have been working with SLGx as far as I look at their protocol spec.  But that driver, is irrelevant for the GreenPakSMBusAdapter )

**Comment by zapta** [comment]
I run a test and was able to reproduce. I got about 1% error rate and the errors are repeatable (exactly same errors on each run) on my GreenPAK device. 

Test program
```python
import random
from greenpak import driver, utils, i2c

port = "/dev/tty.usbmodem1101"

print("\nConnecting.", flush=True)
i2c_driver = i2c.GreenPakI2cAdapter(port=port)
gp_driver = driver.GreenpakDriver(
    i2c_driver, device_type="SLG46826", device_control_code=1)

# Read the entire NVM memory.
print("\nReading entire NVM.", flush=True)
nvm = gp_driver.read_nvm_bytes(0, 256)

# Read random bytes and compare to reference NVM bytes.
print("\nRandom test.", flush=True)
random.seed(0)  # Repeatable rand.
ok_count = 0
err_count = 0
for _ in range(10000):
    a = random.randint(0, 255)
    b = gp_driver.read_nvm_bytes(a, 1)[0]
    if b == nvm[a]:
      status = "ok   "
      ok_count += 1
    else:
       status = "ERROR"
       err_count += 1
    print(f"addr {a:02x}, ref: {nvm[a]:02x}, read: {b:02x}  {status}     {ok_count}/{err_count}")

print(f"Ok: {ok_count}, Errors: {err_count}")
```

The tail of the test
```
...
addr 36, ref: 00, read: 00  ok        9688/74
addr 08, ref: 6d, read: 6d  ok        9689/74
addr 09, ref: 6a, read: 6a  ok        9690/74
addr 9f, ref: 00, read: 00  ok        9691/74
addr 75, ref: 00, read: 00  ok        9692/74
addr 6f, ref: 30, read: 30  ok        9693/74
addr 4a, ref: 00, read: 00  ok        9694/74
addr 5b, ref: 00, read: 00  ok        9695/74
addr 30, ref: 00, read: 00  ok        9696/74
addr f8, ref: 10, read: 00  ERROR     9696/75
addr af, ref: 01, read: 01  ok        9697/75
addr d2, ref: 00, read: 00  ok        9698/75
addr bc, ref: 01, read: 01  ok        9699/75
addr b5, ref: 00, read: 00  ok        9700/75
addr be, ref: 00, read: 00  ok        9701/75
addr f2, ref: 10, read: 10  ok        9702/75
addr eb, ref: 00, read: 00  ok        9703/75
addr 9b, ref: 2c, read: 2c  ok        9704/75
addr bc, ref: 01, read: 01  ok        9705/75
addr 11, ref: 6d, read: 6d  ok        9706/75
addr d4, ref: 00, read: 00  ok        9707/75
addr 0c, ref: 15, read: 15  ok        9708/75
addr 14, ref: 04, read: 04  ok        9709/75
addr a6, ref: 00, read: 00  ok        9710/75
addr 6f, ref: 30, read: 30  ok        9711/75
addr 43, ref: 00, read: 00  ok        9712/75
addr d3, ref: 00, read: 00  ok        9713/75
addr c9, ref: 00, read: 00  ok        9714/75
addr 4e, ref: 00, read: 00  ok        9715/75
addr ca, ref: 01, read: 01  ok        9716/75
addr 9b, ref: 2c, read: 2c  ok        9717/75
addr 4e, ref: 00, read: 00  ok        9718/75
addr 46, ref: 00, read: 00  ok        9719/75
addr 60, ref: 00, read: 00  ok        9720/75
addr 4c, ref: 00, read: 00  ok        9721/75
addr 63, ref: 00, read: 00  ok        9722/75
addr cc, ref: 00, read: 00  ok        9723/75
addr 07, ref: 55, read: 55  ok        9724/75
addr 36, ref: 00, read: 00  ok        9725/75
addr 8c, ref: 00, read: 00  ok        9726/75
addr f2, ref: 10, read: 10  ok        9727/75
addr d1, ref: 00, read: 00  ok        9728/75
addr 93, ref: 00, read: 00  ok        9729/75
addr 7a, ref: 00, read: 00  ok        9730/75
addr 51, ref: 00, read: 00  ok        9731/75
addr 49, ref: 00, read: 00  ok        9732/75
addr 15, ref: 11, read: 11  ok        9733/75
addr bf, ref: 02, read: 02  ok        9734/75
addr bf, ref: 02, read: 02  ok        9735/75
addr 9e, ref: 00, read: 00  ok        9736/75
addr 82, ref: 00, read: 00  ok        9737/75
addr 21, ref: 00, read: 00  ok        9738/75
addr 06, ref: db, read: db  ok        9739/75
addr a0, ref: 00, read: 00  ok        9740/75
addr 39, ref: cd, read: cd  ok        9741/75
addr 11, ref: 6d, read: 6d  ok        9742/75
addr 1d, ref: 00, read: 00  ok        9743/75
addr 6c, ref: 50, read: 50  ok        9744/75
addr 41, ref: 00, read: 00  ok        9745/75
addr 72, ref: 31, read: 31  ok        9746/75
addr cd, ref: 00, read: 00  ok        9747/75
addr 2a, ref: 00, read: 00  ok        9748/75
addr 8a, ref: 00, read: 00  ok        9749/75
addr 4a, ref: 00, read: 00  ok        9750/75
addr d0, ref: 00, read: 00  ok        9751/75
addr 13, ref: 35, read: 35  ok        9752/75
addr 6c, ref: 50, read: 50  ok        9753/75
addr 56, ref: 00, read: 00  ok        9754/75
addr f4, ref: 25, read: 25  ok        9755/75
addr 00, ref: c5, read: c5  ok        9756/75
addr 48, ref: 00, read: 00  ok        9757/75
addr af, ref: 01, read: 01  ok        9758/75
addr ab, ref: 00, read: 00  ok        9759/75
addr df, ref: 00, read: 00  ok        9760/75
addr a9, ref: 02, read: 02  ok        9761/75
addr e9, ref: 00, read: 00  ok        9762/75
addr a6, ref: 00, read: 00  ok        9763/75
addr aa, ref: 01, read: 01  ok        9764/75
addr 06, ref: db, read: db  ok        9765/75
addr 61, ref: 31, read: 31  ok        9766/75
addr 79, ref: 00, read: 00  ok        9767/75
addr c4, ref: 02, read: 02  ok        9768/75
addr 57, ref: 00, read: 00  ok        9769/75
addr 42, ref: 00, read: 00  ok        9770/75
addr ca, ref: 01, read: 01  ok        9771/75
addr 12, ref: 68, read: 68  ok        9772/75
addr 18, ref: 16, read: 16  ok        9773/75
addr cf, ref: 00, read: 00  ok        9774/75
addr 81, ref: 00, read: 00  ok        9775/75
addr ec, ref: 00, read: 00  ok        9776/75
addr 79, ref: 00, read: 00  ok        9777/75
addr 19, ref: b6, read: b6  ok        9778/75
addr d2, ref: 00, read: 00  ok        9779/75
addr d2, ref: 00, read: 00  ok        9780/75
addr e3, ref: 00, read: 00  ok        9781/75
addr 1d, ref: 00, read: 00  ok        9782/75
addr c6, ref: 01, read: 01  ok        9783/75
addr 6c, ref: 50, read: 50  ok        9784/75
addr d0, ref: 00, read: 00  ok        9785/75
addr d6, ref: 00, read: 00  ok        9786/75
addr 0a, ref: b5, read: b5  ok        9787/75
addr fb, ref: 00, read: 00  ok        9788/75
addr 70, ref: 30, read: 30  ok        9789/75
addr 42, ref: 00, read: 00  ok        9790/75
addr 28, ref: 00, read: 00  ok        9791/75
addr 25, ref: 00, read: 00  ok        9792/75
addr 23, ref: 00, read: 00  ok        9793/75
addr b6, ref: 02, read: 02  ok        9794/75
addr 23, ref: 00, read: 00  ok        9795/75
addr 15, ref: 11, read: 11  ok        9796/75
addr 28, ref: 00, read: 00  ok        9797/75
addr 5e, ref: 00, read: 00  ok        9798/75
addr 9f, ref: 00, read: 00  ok        9799/75
addr 49, ref: 00, read: 00  ok        9800/75
addr f2, ref: 10, read: 10  ok        9801/75
addr 7b, ref: 00, read: 00  ok        9802/75
addr 69, ref: 00, read: 00  ok        9803/75
addr 74, ref: 00, read: 00  ok        9804/75
addr a5, ref: 01, read: 01  ok        9805/75
addr b9, ref: 00, read: 00  ok        9806/75
addr 26, ref: 00, read: 00  ok        9807/75
addr 81, ref: 00, read: 00  ok        9808/75
addr fe, ref: 00, read: 00  ok        9809/75
addr 39, ref: cd, read: cd  ok        9810/75
addr 3e, ref: 00, read: 00  ok        9811/75
addr 3f, ref: 00, read: 00  ok        9812/75
addr c8, ref: 00, read: 00  ok        9813/75
addr 7e, ref: 00, read: 00  ok        9814/75
addr 9e, ref: 00, read: 00  ok        9815/75
addr 5e, ref: 00, read: 00  ok        9816/75
addr 8e, ref: 00, read: 00  ok        9817/75
addr f2, ref: 10, read: 10  ok        9818/75
addr db, ref: 00, read: 00  ok        9819/75
addr 6b, ref: 80, read: 80  ok        9820/75
addr fd, ref: 00, read: 00  ok        9821/75
addr e1, ref: 00, read: 00  ok        9822/75
addr c3, ref: 00, read: 00  ok        9823/75
addr 01, ref: b5, read: b5  ok        9824/75
addr 4a, ref: 00, read: 00  ok        9825/75
addr ba, ref: 00, read: 00  ok        9826/75
addr 8f, ref: 00, read: 00  ok        9827/75
addr 33, ref: 00, read: 00  ok        9828/75
addr 71, ref: 30, read: 30  ok        9829/75
addr 09, ref: 6a, read: 6a  ok        9830/75
addr 80, ref: 00, read: 00  ok        9831/75
addr 5d, ref: 00, read: 00  ok        9832/75
addr 9c, ref: 90, read: 90  ok        9833/75
addr 58, ref: 00, read: 00  ok        9834/75
addr 64, ref: 11, read: 11  ok        9835/75
addr b7, ref: 00, read: 00  ok        9836/75
addr 90, ref: 49, read: 49  ok        9837/75
addr 13, ref: 35, read: 35  ok        9838/75
addr 2a, ref: 00, read: 00  ok        9839/75
addr e9, ref: 00, read: 00  ok        9840/75
addr 1d, ref: 00, read: 00  ok        9841/75
addr 07, ref: 55, read: 55  ok        9842/75
addr 2c, ref: 00, read: 00  ok        9843/75
addr 06, ref: db, read: db  ok        9844/75
addr 70, ref: 30, read: 30  ok        9845/75
addr 43, ref: 00, read: 00  ok        9846/75
addr 0d, ref: 03, read: 03  ok        9847/75
addr b6, ref: 02, read: 02  ok        9848/75
addr 57, ref: 00, read: 00  ok        9849/75
addr 02, ref: 55, read: 55  ok        9850/75
addr 3c, ref: c1, read: c1  ok        9851/75
addr be, ref: 00, read: 00  ok        9852/75
addr 3c, ref: c1, read: c1  ok        9853/75
addr 42, ref: 00, read: 00  ok        9854/75
addr ab, ref: 00, read: 00  ok        9855/75
addr 77, ref: 00, read: 00  ok        9856/75
addr 15, ref: 11, read: 11  ok        9857/75
addr 0e, ref: 00, read: 00  ok        9858/75
addr 98, ref: 90, read: 90  ok        9859/75
addr fb, ref: 00, read: 00  ok        9860/75
addr f2, ref: 10, read: 10  ok        9861/75
addr 1d, ref: 00, read: 00  ok        9862/75
addr 14, ref: 04, read: 04  ok        9863/75
addr d9, ref: 00, read: 00  ok        9864/75
addr b8, ref: 01, read: 01  ok        9865/75
addr d1, ref: 00, read: 00  ok        9866/75
addr 59, ref: 00, read: 00  ok        9867/75
addr 2a, ref: 00, read: 00  ok        9868/75
addr 67, ref: 10, read: 10  ok        9869/75
addr 6f, ref: 30, read: 30  ok        9870/75
addr fc, ref: 00, read: 00  ok        9871/75
addr 59, ref: 00, read: 00  ok        9872/75
addr 39, ref: cd, read: cd  ok        9873/75
addr 33, ref: 00, read: 00  ok        9874/75
addr e0, ref: 00, read: 00  ok        9875/75
addr 49, ref: 00, read: 00  ok        9876/75
addr 0b, ref: 3d, read: 3d  ok        9877/75
addr 4e, ref: 00, read: 00  ok        9878/75
addr 65, ref: 11, read: 11  ok        9879/75
addr 81, ref: 00, read: 00  ok        9880/75
addr 9f, ref: 00, read: 00  ok        9881/75
addr 71, ref: 30, read: 30  ok        9882/75
addr f2, ref: 10, read: 10  ok        9883/75
addr a5, ref: 01, read: 01  ok        9884/75
addr 90, ref: 49, read: 49  ok        9885/75
addr 4f, ref: 00, read: 00  ok        9886/75
addr 24, ref: 00, read: 00  ok        9887/75
addr c7, ref: 00, read: 00  ok        9888/75
addr 05, ref: 48, read: 48  ok        9889/75
addr fb, ref: 00, read: 00  ok        9890/75
addr 77, ref: 00, read: 00  ok        9891/75
addr 1e, ref: d3, read: d3  ok        9892/75
addr 14, ref: 04, read: 04  ok        9893/75
addr ca, ref: 01, read: 01  ok        9894/75
addr 2f, ref: 00, read: 00  ok        9895/75
addr fc, ref: 00, read: 00  ok        9896/75
addr ac, ref: 00, read: 00  ok        9897/75
addr ec, ref: 00, read: 00  ok        9898/75
addr bf, ref: 02, read: 02  ok        9899/75
addr a2, ref: 80, read: 80  ok        9900/75
addr 69, ref: 00, read: 00  ok        9901/75
addr 15, ref: 11, read: 11  ok        9902/75
addr 0a, ref: b5, read: b5  ok        9903/75
addr 6b, ref: 80, read: 80  ok        9904/75
addr a9, ref: 02, read: 02  ok        9905/75
addr a0, ref: 00, read: 00  ok        9906/75
addr 74, ref: 00, read: 00  ok        9907/75
addr ee, ref: 00, read: 00  ok        9908/75
addr ad, ref: 02, read: 02  ok        9909/75
addr a9, ref: 02, read: 02  ok        9910/75
addr 50, ref: 00, read: 00  ok        9911/75
addr 4d, ref: 00, read: 00  ok        9912/75
addr 4d, ref: 00, read: 00  ok        9913/75
addr ab, ref: 00, read: 00  ok        9914/75
addr 6e, ref: 00, read: 00  ok        9915/75
addr c1, ref: 01, read: 01  ok        9916/75
addr b3, ref: 01, read: 01  ok        9917/75
addr da, ref: 00, read: 00  ok        9918/75
addr bb, ref: 02, read: 02  ok        9919/75
addr bd, ref: 00, read: 00  ok        9920/75
addr ab, ref: 00, read: 00  ok        9921/75
addr 00, ref: c5, read: c5  ok        9922/75
addr 05, ref: 48, read: 48  ok        9923/75
addr 14, ref: 04, read: 04  ok        9924/75
addr c1, ref: 01, read: 01  ok        9925/75
Ok: 9925, Errors: 75
```

**Comment by zapta** [comment]
If I understand you correctly, you propose to move this write/read snippet https://github.com/zapta/greenpak/blob/main/src/greenpak/driver.py#L127 to the base class of the i2c drivers https://github.com/zapta/greenpak/blob/main/src/greenpak/i2c.py#L8 such that you can implement it correctly with your i2c driver. This sounds a good idea.

So let's say that we add the to the I2c base class this new write-then-read method:

```python
def write_read_request(self, i2c_addr: int, write_data: bytearray, read_count: int ) -> bytearray
```

Now thinking of the specification of this method, what will be the max ``len(write_data)`` and the max ``read_count`` that the implementation is expected to handle? The reason I ask is that this method cannot chunk the writes and reads (since write_data is greenpak specific) and you mentioned that you have some limitation of 32 bytes (?).  

For example, the specification can be that ``len(write_data) <= 32`` and ``read_count <= 32`` and the greenpack driver will do the greenpak aware chunking. Does this make sense to you?

**Comment by dry-75** [comment]
def write_read_request(self, i2c_addr: int, write_data: bytearray, read_count: int ) -> bytearray

Let's also note that - as per current Gp' Driver.py code - the bytearray should/shall contain the slg' register address as its first element, this is what the code does.  Perhaps we should just add a comment to that interface, for implementors.

> Thinking of the specification of this method, what will be the max len(write_data) and the max read_count that the implementation is expected to handle? 

I would think of:  1. require class GreenPakI2cInterface to also implement require constants like max read/write on bus supported, either that can be just used directly, or checked witha method. These could have  defaults which could be overwritten by the implementation.  Say,  inside GreenPakI2cInterface,    MAX_<WR||RD>_LEN_SUPPORTED, or method 
def get_iface_info() which woudl return a structure with few of those constants - which then can be extend if need arises.
Thus for e.g. , if your i2c actual driver (i2c adapter device?)  supports full 256 bytes in single op, well it will set those contants as required. My drive that I wish to plug into gp driver, would define that to 32.

Ultimately 2. an implementation will throw / raise exception if something is requested beyond limits, which is also one way to handle it : user will get exception and adjust his/her expectation . The lazy way . But we should still throw/raise exceptions of course. 

From higher level / lets say your perspective,   driver.py as it now, can require / expect that, the lower level interface need to handle chunking:  that is, as is the smbus2 adapter does now to read driver.py' request of full memory segment of 256 bytes. I don't see issue with that.  As I see the Gp "driver" - its the application / peripheral higher level driver above the i2c bus. One way , not necc. best way, is to keep it  clean of those a bit lower level details  - i mean the physical and sw driver for bus to get bytes in/out.

**Comment by zapta** [comment]
The implementation providing it's max capabilities looks as a simple and
clean approach. I will define such a method and will send you to take a
look before I change the logic.

**Comment by dry-75** [comment]
If you asking with respect to my original post/report:  then this is misunderstanding, I have reported the bug in relation specifically to the smbus adapter that that (I myself) have contributed. Nothing to do with greenpack driver higher which processes the bytes.
In this case, its the random address reads of anywhere within the memory block always of less than 256 bytes.

If you asking about my comment on the GreenPakI2cDriver() and the __i2c.stop(), I cannot comment on that if that works, because I don't use it, I never tested it.  My comment was on the code as is, vs what the datasheet says how that protocol should be, wrt to read requests.

**Comment by zapta** [comment]
I see. The combined transaction is required with a multi master I2C not required with a single master.

Having separate read/write operations results with a simple driver API and allows implementations to chunk the reads and writes if needed.

**Comment by dry-75** [comment]
This was resolved.
