### ISSUE TITLE
syntax error in i2c_adapter f-string

### ISSUE THREAD

**Issue by dry-75** [zapta/greenpak#6]
I understand this is a different project or subproject, the i2c_adapter, but anyhow:

Traceback (most recent call last):
  File "/home/alarm/greenpak/test/smb_test.py", line 6, in <module>
    from greenpak import driver, utils, i2c
  File "/home/alarm/greenpak/.venv/lib/python3.10/site-packages/greenpak/driver.py", line 7, in <module>
    from greenpak.i2c import GreenPakI2cInterface
  File "/home/alarm/greenpak/.venv/lib/python3.10/site-packages/greenpak/i2c.py", line 3, in <module>
    from i2c_adapter import I2cAdapter
  File "/home/alarm/greenpak/.venv/lib/python3.10/site-packages/i2c_adapter/__init__.py", line 36
    print(f"Adapter info: {adapter_info.hex(" ")}", flush=True)
                                                  ^
SyntaxError: f-string: unmatched '('

Seems easy fix to replace outer " " with ' '

**Comment by zapta** [comment]
Thanks. I fixed it and pushed a new version to pypi.  https://pypi.org/project/i2c-adapter/0.2.21

It's interesting that it worked for me with python Python 3.12.1 on Mac os. I think it interpreted it as two concatenated strings and ' ' is also the default for hex().

```
Connecting.
Adapter info: 49 32 43 03 01 00 00
```

**Comment by zapta** [comment]
BTW, if you are using the I2c Adapter, this is my favorite board. USB C connector, QWIIC connector for I2C and built in pullups. I wrapped it with a clear shrink-wrap and it's very handy. The Raspberry Pico also works well though.

https://www.sparkfun.com/products/18288

**Comment by dry-75** [comment]
@zapta we are not at present, but because its included into greenpak driver library by default, we get the issue.
I hope that, after you have merged the pull request outstanding, the dependency may go away : see pull request on write_read method.
